apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-4ygj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-4ygj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-4ygj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-4ygj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-4ygj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dyil-tenant/rhtap-demo-app/hacbs-test-project-4ygj@sha256:74349e0643887cefb562a2430658f626f44a260843b5d1c0f220dd982477e267
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
